#application.yml
server:
  port: 9001
  servlet:
    context-path: /pri

logging:
  level:
    root: info
    jdbc: off
    sql only: info


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: privit.project



#    mybatis.mapper-locations=classpath:/mapper/**/*.xml
#    mybatis.type-aliases-package=hyosung.lts

#logging:
 # level:
  #  jdbc: off
   #   sqlonly: info
#logging.level.jdbc.sqlonly=info





#    spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    spring.datasource.url=jdbc:log4jdbc:postgresql://10.11.16.171:5432/hssnopdev
#    spring.datasource.username=hs_user
#    spring.datasource.password=hs_user86

